name:                haskell-principles
version:             0.1.0.0
github:              "alextes/haskell-principles"
license:             BSD3
author:              "Alexander Tesfamichael"
maintainer:          "alex.tesfamichael@gmail.com"
copyright:           "2018 Alexander Tesfamichael"

extra-source-files:
- README.md

description: Repo for Haskell From First Principles exercises.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-principles-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-principles

tests:
  haskell-principles-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-principles
